### ISSUE TITLE
AutoLayout 与 UIScrollView 合作时让UIScrollView的宽度适配屏幕宽度Tips？

### ISSUE THREAD

**Issue by alfredcc** [nixzhu/dev-blog#11]
使用UIScrollView 和 AutoLayout 的时候，因为一般情况下往 UIScrollView 填充组件的时候对组件高度限制很少，都是从上往下排列，而且用户的习惯也是从上往下滚动浏览，而不是从左往右浏览。所以经常出现的场景是需要我们给定组件的宽度约束等于屏幕的宽度，这样来使UIScrollView达到类似UITableView的浏览效果。但由于iPhone6，6P的屏幕宽度，与iPhone5s以前的宽度不一样，我每次的做法都是根据不同设备去 manually 改变组件的宽度约束。请问有没有更好的方法去实现呢？

**Comment by nixzhu** [comment]
@alfredcc 这非常容易，Demo 里的 Tab B 就是示例。注意 Slider 的约束，它右边有一个到 View 的约束，这个约束可以确保 UIScrollView contentView 的宽度和屏幕一致。因为 AutoLayout 的特性，链接到 UIScrollView 上边和左边的约束“天然的”和View“等齐”，所以要注意的是右边和下边的约束。因为 View 的宽度和屏幕一样，所以自然要利用它。

希望我的解释足够清楚！

**Comment by alfredcc** [comment]
恩 浏览 Demo 里面的相关的约束能够清楚理解了。非常感谢！
