### ISSUE TITLE
NSCache 中 insert 方法是否要加 `e.prevByCost = entry` 讨论

### ISSUE THREAD

**Issue by alfredcc** [nixzhu/dev-blog#14]
我的理解是 如果加了 `e.prevByCost = entry` 反而会出错。因为如果在 insert 的时候只有一个 cacheEntry ,而且这个 cacheEntry 的 “价值” 正好比新的 cacheEntry 大，这时新 cacheEntry 排在第一个，他是没有prevByCost 的

**Comment by alfredcc** [comment]
另外一点 _byCost 如果没有 prevByCost 其实也并没有破坏 NSCache 中整个 enties 的链表排列

**Comment by alfredcc** [comment]
第一条我理解错了抱歉，我也觉得应该是要加的。

**Comment by nixzhu** [comment]
你的考虑很好，最好的办法是根据代码流程，模拟插入、删除一些有 cost 的 entry，做几个测试样例，理解会更深刻。不过NSCache 代码错误的可能性很小。有时间可配几张图片。

也可将 NSCache 的代码单独拷贝出来，自己加入一些流程提示代码，并在插入或删除时打印“链表”，再用例子测试即可。

**Comment by alfredcc** [comment]
恩，确实，还有很多地方没有理解的很深刻，感谢～

**Comment by nixzhu** [comment]
我也是第一次看这种 Foundation 的代码，互相交流学习
