### ISSUE TITLE
[文章评论] 能偶尔用上的 awk

### ISSUE THREAD

**Issue by CodeEagle** [nixzhu/dev-blog#26]
关于文章中生成的方式，资源更新有点不太及时

所以基于此做了个`Xcode`的`Run Script`

项目在此[ImageResourceGenerator](https://github.com/CodeEagle/ImageResourceGenerator)

**Comment by amitbha** [comment]
~~~
for i in $(ls *.imageset | sed -r 's/\.imageset//; s/_(.)/\U\1/'); do
    echo "|$i|"
done
~~~
- `ls -1 *.imageset`：一行一个文件名
- `s/\.imageset//`：替换 .imageset 为空
- `s/_(.)/\U\1/`：替换时反向引用+大写操作
